version: "3"

services:
  mysqldb:
   container_name: mysqldb
   image: mysql:8
   restart: unless-stopped
   ports:
    - 3307:3306
   environment:
    MYSQL_DATABASE: achatdb
    MYSQL_ROOT_PASSWORD:
   volumes:
     - /home/mysql/data:/var/lib/mysql --user 1000

  spring_app:
   image: fir4s269/achatapp
   container_name: achatprojet
   restart: on-failure
   ports:
    - 8089:8089
   environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/achatdb?useSSL=false&allowPublicKeyRetrieval=true&useLegacyDatetimeCode=false&serverTimezone=UTC
   depends_on:
    - mysqldb 
